using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestClass
{
    class ModelData
    {
        public ModelData()
        {
            FillHeaderList();
            FillGHWList();
        }

        public List<string> greatestHeaderWordList {get; private set;}
        public List<string> headerList {get; private set;}
        private void FillHeaderList()
        {
            headerList = new List<string>{
            "\"Acquirer's Indemnification Basket (HOST CURRENCY\"",
"\"2Acquirer's Indemnification Basket (USD\"",
"\"Acquirer's Indemnification Cap (HOST\"",
"\"2Acquirer's Indemnification Cap (USD\"",
"\"Acquiror CUSI\"",
"\"Acquiror Accts Payable LTM (host mil\"",
"\"Acquiror SIC Code\"",
"\"2Acquiror SIC Code\"",
"\"Acquiror Province (Code\"",
"\"Acquiror Cash LTM ($ mil\"",
"\"Acquiror Cit\"",
"\"Acq Closing Price 1 Day Prior to Ann($\"",
"\"Acq Closing Price 1 Wk Prior to Ann($\"",
"\"Acq Closing Price 4 Wks Prior to Ann($\"",
"\"Acquiror Common Div LTM ($ mil\"",
"\"Acquiror Common Equity LTM ($ mil\"",
"\"Acquiror Common Shares LTM (mil\"",
"\"Acquiror Datastream Cod\"",
"\"Acquiror Deferred Taxes LTM ($ mil\"",
"\"Acquiror Deferred Taxes LTM (host mil\"",
"\"Acquiror Immediate Parent CUSI\"",
"\"Acquiror Full Nam\"",
"\"Acquiror Natio\"",
"\"Acquiror Pre-tax Income LTM ($ mil\"",
"\"Acquiror Pre-tax Income LTM (host mil\"",
"\"Acquiror Primary Ticker Symbo\"",
"\"Acquiror Prop Plant Equip LTM ($ mil\"",
"\"Acq. Public Statu\"",
"\"Acquiror's price per shar\"",
"\"Host Curr Acquiror's price per shar\"",
"\"Acquiror Significant Individua\"",
"\"Acquiror Stat\"",
"\"2Acquiror Stat\"",
"\"Acq. State of Inc\"",
"\"Acquiror State of Incorporatio\"",
"\"Acquiror State Region Cod\"",
"\"Acquiror State Regio\"",
"\"Acquiror Stock Exchange (Code\"",
"\"Acquiror Stock Exchange (Name\"",
"\"Acquiror Street Addres\"",
"\"Acquiror Taxes LTM ($ mil\"",
"\"Acquiror Taxes LTM (host mil\"",
"\"Acquiror's termination fee (mil\"",
"\"Acquiror Ticker Symbo\"",
"\"Acquiror Ultimate Parent CUSI\"",
"\"Acquiror Ultimate Parent Primary Ticker Symbo\"",
"\"Acquiror Ultimate Parent Street Address \"",
"\"2Acquiror Ultimate Parent Street Address \"",
"\"Acquiror Ultimate Parent Ticker Symbo\"",
"\"Analyst Estimated Value ($mil\"",
"\"Host Curr. Analyst Estimated Value (mil\"",
"\"Target Bankrup\"",
"\"Acquiror Blank Check Company Flag(Y/N\"",
"\"Block Purchase\"",
"\"Target Cash & Mktbl. Securities One Year Prior ($ mil\"",
"\"2Target Cash & Mktbl. Securities Two Years Prior ($ mil\"",
"\"3Target Cash & Mktbl. Securities Three Years Prior ($ mil\"",
"\"4Target Cash & Mktbl. Securities Four Years Prior ($ mil\"",
"\"5Target Cash & Mktbl. Securities Five Years Prior ($ mil\"",
"\"6Target Cash & Mktbl. Securities Most Recent Quarter ($ mil\"",
"\"Challenged Deal Acquiror CUSI\"",
"\"Challenged Dea\"",
"\"Challenged Deal Target CUSI\"",
"\"Collar Statu\"",
"\"Asset Locku\"",
"\"Back-End Defens\"",
"\"Flip- Over Defens\"",
"\"Greenmai\"",
"\"Target Locku\"",
"\"Lockup Flag (Y/N\"",
"\"Pacman Defens\"",
"\"Poison Pil\"",
"\"Recap. Defens\"",
"\"Repurchase Defens\"",
"\"Scorched Earth Defens\"",
"\"Self- Tender Defens\"",
"\"Stock Locku\"",
"\"Defensive Tactic\"",
"\"Defens\"",
"\"Voting Plan Defens\"",
"\"White Knight Defens\"",
"\"White Squir\"",
"\"Deferred Inc. Taxes & Charges On Date of Financial\"",
"\"Target Deferred Taxes and Charges LTM ($mil\"",
"\"Definitive Agreement (Y/N\"",
"\"Definitive Agreement Dat\"",
"\"Estimated Acquiror Effective Income Tax Rat\"",
"\"Expected Synergies After Taxes ($ mil\"",
"\"2Expected Synergies After Taxes (Host mil\"",
"\"Expected Synergies Before Taxes ($mil\"",
"\"2Expected Synergies Before Taxes (Host mil\"",
"\"Fiduciary Termination Right (Y/N\"",
"\"Forecasted Pre-Tax Income Current Fiscal Year ($ Mil\"",
"\"2Forecasted Pre-Tax Income Current Fiscal Year (Euro Mil\"",
"\"3Forecasted Pre-Tax Income Current Fiscal Year (Host Mil\"",
"\"Forecasted Pre-Tax Income Next Twelve Months ($ Mil\"",
"\"2Forecasted Pre-Tax Income Next Twelve Months (Euro Mil\"",
"\"3Forecasted Pre-Tax Income Next Twelve Months (Host Mil\"",
"\"Forecasted Pre-Tax Income Year Two ($ Mil\"",
"\"2Forecasted Pre-Tax Income Year Two (Euro Mil\"",
"\"3Forecasted Pre-Tax Income Year Two (Host Mil\"",
"\"Investor Cusi\"",
"\"Investor Immediate Parent 6-digit CUSI\"",
"\"Investor Immediate Parent Cusi\"",
"\"Target CUSI\"",
"\"Date Announce\"",
"\"Transaction Comparable: Deal Numbe\"",
"\"Deal Numbe\"",
"\"Related Deal Numbe\"",
"\"Related Deal Cod\"",
"\"2Related Deal Numbe\"",
"\"Competing Bid Deal Cod\""
            };
        }

        private void FillGHWList()
        {
            greatestHeaderWordList = new List<string>{
                "Acquirer's",
"Acquirer's",
"Acquirer's",
"Acquirer's",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror SIC Codes",
"Acquiror",
"Acquiror Cash",
"Acquiror City",
"Acq Closing",
"Acq Closing",
"Acq Closing",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror Full Name",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Public",
"Acquiror's price",
"Host Curr",
"Acquiror",
"Acquiror",
"Acquiror State",
"Acq.",
"Incorporation",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror Street Address",
"Acquiror Taxes",
"Acquiror Taxes",
"Acquiror's",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror Ultimate Parent",
"Acquiror Ultimate Parent",
"Acquiror",
"Analyst",
"Host Curr.",
"Target",
"Acquiror",
"Block",
"Cash & Mktbl.",
"Target",
"Target",
"Target",
"Target",
"Target",
"Challenged",
"Challenged",
"Challenged",
"Collar",
"Asset",
"Back-End",
"Flip-",
"Greenmail",
"Target",
"Lockup",
"Pacman",
"Poison",
"Recap.",
"Repurchase",
"Scorched",
"Tender",
"Stock",
"Defensive Tactics",
"Defense",
"Voting",
"White",
"White",
"Deferred Inc.",
"Deferred",
"Definitive",
"Definitive",
"Estimated Acquiror",
"Expected Synergies",
"Expected Synergies",
"Expected Synergies",
"Expected Synergies",
"Fiduciary",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Investor",
"Investor",
"Investor",
"Target",
"Announced",
"Transaction Comparable:",
"Deal",
"Related",
"Related",
"Related",
"Competing"
            };
        }

    }
}
