using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestClass
{
    public class ModelData
    {
        public ModelData()
        {
            FillHeaderList();
            FillGHWList();
        }

        public List<string> greatestHeaderWordList { get; private set; }
        public List<string> headerList { get; private set; }
        private void FillHeaderList()
        {
            headerList = new List<string>{
"\"Acquirer's Indemnification Basket (HOST CURRENCY)\"",
"\"2Acquirer's Indemnification Basket (USD)\"",
"\"Acquirer's Indemnification Cap (HOST)\"",
"\"2Acquirer's Indemnification Cap (USD)\"",
"\"Acquiror CUSIP\"",
"\"Acquiror Accts Payable LTM (host mil)\"",
"\"Acquiror SIC Codes\"",
"\"2Acquiror SIC Codes\"",
"\"Acquiror Province (Code)\"",
"\"Acquiror Cash LTM ($ mil)\"",
"\"Acquiror City\"",
"\"Acq Closing Price 1 Day Prior to Ann($)\"",
"\"Acq Closing Price 1 Wk Prior to Ann($)\"",
"\"Acq Closing Price 4 Wks Prior to Ann($)\"",
"\"Acquiror Common Div LTM ($ mil)\"",
"\"Acquiror Common Equity LTM ($ mil)\"",
"\"Acquiror Common Shares LTM (mil)\"",
"\"Acquiror Datastream Code\"",
"\"Acquiror Deferred Taxes LTM ($ mil)\"",
"\"Acquiror Deferred Taxes LTM (host mil)\"",
"\"Acquiror Immediate Parent CUSIP\"",
"\"Acquiror Full Name\"",
"\"Acquiror Nation\"",
"\"Acquiror Pre-tax Income LTM ($ mil)\"",
"\"Acquiror Pre-tax Income LTM (host mil)\"",
"\"Acquiror Primary Ticker Symbol\"",
"\"Acquiror Prop Plant Equip LTM ($ mil)\"",
"\"Acq. Public Status\"",
"\"Acquiror's price per share\"",
"\"Host Curr Acquiror's price per share\"",
"\"Acquiror Significant Individual\"",
"\"Acquiror State\"",
"\"2Acquiror State\"",
"\"Acq. State of Inc.\"",
"\"Acquiror State of Incorporation\"",
"\"Acquiror State Region Code\"",
"\"Acquiror State Region\"",
"\"Acquiror Stock Exchange (Code)\"",
"\"Acquiror Stock Exchange (Name)\"",
"\"Acquiror Street Address\"",
"\"Acquiror Taxes LTM ($ mil)\"",
"\"Acquiror Taxes LTM (host mil)\"",
"\"Acquiror's termination fee (mil)\"",
"\"Acquiror Ticker Symbol\"",
"\"Acquiror Ultimate Parent CUSIP\"",
"\"Acquiror Ultimate Parent Primary Ticker Symbol\"",
"\"Acquiror Ultimate Parent Street Address 1\"",
"\"2Acquiror Ultimate Parent Street Address 2\"",
"\"Acquiror Ultimate Parent Ticker Symbol\"",
"\"Analyst Estimated Value ($mil)\"",
"\"Host Curr. Analyst Estimated Value (mil)\"",
"\"Target Bankrupt\"",
"\"Acquiror Blank Check Company Flag(Y/N)\"",
"\"Block Purchases\"",
"\"Target Cash & Mktbl. Securities One Year Prior ($ mil)\"",
"\"2Target Cash & Mktbl. Securities Two Years Prior ($ mil)\"",
"\"3Target Cash & Mktbl. Securities Three Years Prior ($ mil)\"",
"\"4Target Cash & Mktbl. Securities Four Years Prior ($ mil)\"",
"\"5Target Cash & Mktbl. Securities Five Years Prior ($ mil)\"",
"\"6Target Cash & Mktbl. Securities Most Recent Quarter ($ mil)\"",
"\"Challenged Deal Acquiror CUSIP\"",
"\"Challenged Deal\"",
"\"Challenged Deal Target CUSIP\"",
"\"Collar Status\"",
"\"Asset Lockup\"",
"\"Back-End Defense\"",
"\"Flip- Over Defense\"",
"\"Greenmail\"",
"\"Target Lockup\"",
"\"Lockup Flag (Y/N)\"",
"\"Pacman Defense\"",
"\"Poison Pill\"",
"\"Recap. Defense\"",
"\"Repurchase Defense\"",
"\"Scorched Earth Defense\"",
"\"Self- Tender Defense\"",
"\"Stock Lockup\"",
"\"Defensive Tactics\"",
"\"Defense\"",
"\"Voting Plan Defense\"",
"\"White Knight Defense\"",
"\"White Squire\"",
"\"Deferred Inc. Taxes & Charges On Date of Financials\"",
"\"Target Deferred Taxes and Charges LTM ($mil)\"",
"\"Definitive Agreement (Y/N)\"",
"\"Definitive Agreement Date\"",
"\"Estimated Acquiror Effective Income Tax Rate\"",
"\"Expected Synergies After Taxes ($ mil)\"",
"\"2Expected Synergies After Taxes (Host mil)\"",
"\"Expected Synergies Before Taxes ($mil)\"",
"\"2Expected Synergies Before Taxes (Host mil)\"",
"\"Fiduciary Termination Right (Y/N)\"",
"\"Forecasted Pre-Tax Income Current Fiscal Year ($ Mil)\"",
"\"2Forecasted Pre-Tax Income Current Fiscal Year (Euro Mil)\"",
"\"3Forecasted Pre-Tax Income Current Fiscal Year (Host Mil)\"",
"\"Forecasted Pre-Tax Income Next Twelve Months ($ Mil)\"",
"\"2Forecasted Pre-Tax Income Next Twelve Months (Euro Mil)\"",
"\"3Forecasted Pre-Tax Income Next Twelve Months (Host Mil)\"",
"\"Forecasted Pre-Tax Income Year Two ($ Mil)\"",
"\"2Forecasted Pre-Tax Income Year Two (Euro Mil)\"",
"\"3Forecasted Pre-Tax Income Year Two (Host Mil)\"",
"\"Investor Cusip\"",
"\"Investor Immediate Parent 6-digit CUSIP\"",
"\"Investor Immediate Parent Cusip\"",
"\"Target CUSIP\"",
"\"Date Announced\"",
"\"Transaction Comparable: Deal Number\"",
"\"Deal Number\"",
"\"Related Deal Number\"",
"\"Related Deal Code\"",
"\"2Related Deal Number\"",
"\"Competing Bid Deal Code\""

            };
        }

        private void FillGHWList()
        {
            greatestHeaderWordList = new List<string>{
                "Acquirer's",
"Acquirer's",
"Acquirer's",
"Acquirer's",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror SIC Codes",
"Acquiror",
"Acquiror Cash",
"Acquiror City",
"Acq Closing",
"Acq Closing",
"Acq Closing",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror Full Name",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Public",
"Acquiror's price",
"Host Curr",
"Acquiror",
"Acquiror",
"Acquiror State",
"Acq.",
"Incorporation",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror Street Address",
"Acquiror Taxes",
"Acquiror Taxes",
"Acquiror's",
"Acquiror",
"Acquiror",
"Acquiror",
"Acquiror Ultimate Parent",
"Acquiror Ultimate Parent",
"Acquiror",
"Analyst",
"Host Curr.",
"Target",
"Acquiror",
"Block",
"Cash & Mktbl.",
"Target",
"Target",
"Target",
"Target",
"Target",
"Challenged",
"Challenged",
"Challenged",
"Collar",
"Asset",
"Back-End",
"Flip-",
"Greenmail",
"Target",
"Lockup",
"Pacman",
"Poison",
"Recap.",
"Repurchase",
"Scorched",
"Tender",
"Stock",
"Defensive Tactics",
"Defense",
"Voting",
"White",
"White",
"Deferred Inc.",
"Deferred",
"Definitive",
"Definitive",
"Estimated Acquiror",
"Expected Synergies",
"Expected Synergies",
"Expected Synergies",
"Expected Synergies",
"Fiduciary",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Forecasted",
"Investor",
"Investor",
"Investor",
"Target",
"Announced",
"Transaction Comparable:",
"Deal",
"Related",
"Related",
"Related",
"Competing"
            };
        }

    }
}
